variable "db_storage" {}
variable "db_engine_version" {}
variable "db_instance_class" {}
variable "db_name" {}
variable "db_user" {}
variable "db_password" {}
variable "db_subnet_group_name" {}
variable "vpc_security_group_ids" {}
variable "db_identifier" {}
variable "skip_db_snapshot" {}
variable "backup_window" {}
variable "backup_retention_period" {}
variable "maintenance_window" {}
