variable "instance_count" {}
variable "key_name" {}
variable "public_key_path" {}
variable "instance_type" {}
variable "public_sg" {}
variable "public_subnets" {}
variable "vol_size" {}
variable "lb_target_group_arn" {}
variable "tg_port" {}
