variable "instance_count" {}
variable "key_name" {}
variable "public_key_path" {}
variable "instance_type" {}
variable "public_sg" {}
variable "public_subnets" {}
variable "vol_size" {}
variable "lb_target_group_arn" {}
variable "tg_port" {}
variable "db_endpoint" {}
variable "db_user" {}
variable "db_password" {}
variable "db_name" {}
variable "db_user_data_path" {}
variable "token" {}
