apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
        - name: webatspeed-fe
          image: webatspeed/webatspeed-fe:0.4.0
          ports:
            - containerPort: 3000
              hostPort: 8000
