apiVersion: v1
kind: ConfigMap
metadata:
  name: mongodb-common-scripts
data:
  readiness-probe.sh: |
    #!/bin/bash
    mongosh --eval 'db.hello().isWritablePrimary || db.hello().secondary' | grep 'true'
  ping-mongodb.sh: |
    #!/bin/bash
    mongosh --eval "db.adminCommand('ping')"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mongodb-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongodb
  labels:
    app: mongodb
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mongodb
  template:
    metadata:
      labels:
        app: mongodb
    spec:
      securityContext:
        fsGroup: 1001
      containers:
        - name: mongodb
          image: mongodb/mongodb-community-server:7.0.1-ubi8
          imagePullPolicy: "IfNotPresent"
          args: ["--dbpath","/data/db"]
          env:
            - name: MONGODB_INITDB_ROOT_USERNAME
              valueFrom:
                secretKeyRef:
                  name: mongo-credentials
                  key: mongodb-root-username
            - name: MONGODB_INITDB_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mongo-credentials
                  key: mongodb-root-password
            - name: MONGODB_INITDB_DATABASE
              value: subscription
            - name: ALLOW_EMPTY_PASSWORD
              value: "no"
            - name: MONGODB_DISABLE_JAVASCRIPT
              value: "no"
            - name: MONGODB_ENABLE_DIRECTORY_PER_DB
              value: "no"
          ports:
            - name: mongodb
              containerPort: 27017
          livenessProbe:
            exec:
              command:
                - /data/scripts/ping-mongodb.sh
            initialDelaySeconds: 30
            periodSeconds: 20
            timeoutSeconds: 10
            successThreshold: 1
            failureThreshold: 6
          readinessProbe:
            exec:
              command:
                - /data/scripts/readiness-probe.sh
            initialDelaySeconds: 5
            periodSeconds: 10
            timeoutSeconds: 5
            successThreshold: 1
            failureThreshold: 6
          volumeMounts:
            - mountPath: /data/scripts
              name: common-scripts
            - mountPath: /data/db
              name: mongo-data-dir
      volumes:
        - name: common-scripts
          configMap:
            name: mongodb-common-scripts
            defaultMode: 0550
        - name: mongo-data-dir
          persistentVolumeClaim:
            claimName: mongodb-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: mongodb
  labels:
    app: mongodb
spec:
  ports:
    - port: 27017
      protocol: TCP
  selector:
    app: mongodb
