apiVersion: apps/v1
kind: Deployment
metadata:
  name: subscription-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: subscription-service
  template:
    metadata:
      labels:
        app: subscription-service
    spec:
      containers:
        - name: webatspeed-subscription-service
          image: webatspeed/webatspeed-subscription-service:0.1.0
          ports:
            - containerPort: 8080
          env:
            - name: MONGO_HOST
              value: mongodb
            - name: MONGO_USER
              valueFrom:
                secretKeyRef:
                  name: mongo-credentials
                  key: username
            - name: MONGO_PASS
              valueFrom:
                secretKeyRef:
                  name: mongo-credentials
                  key: password
            - name: AWS_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  name: ses-credentials
                  key: username
            - name: AWS_SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: ses-credentials
                  key: password
            - name: AWS_DEFAULT_REGION
              valueFrom:
                secretKeyRef:
                  name: ses-credentials
                  key: region
            - name: EMAIL
              valueFrom:
                secretKeyRef:
                  name: ses-credentials
                  key: email
            - name: CORS_ORIGIN
              value: "http://*"
---
apiVersion: v1
kind: Service
metadata:
  name: subscription-service
  labels:
    app: subscription-service
spec:
  ports:
    - port: 8080
      protocol: TCP
  selector:
    app: subscription-service
